name: CI
on:
    workflow_dispatch:  # Allow manual triggering
    pull_request:
    push:
        branches: [master,main]

jobs:
    check:
        runs-on: ubuntu-latest
        #env:
        #    DEST_DIR: /home/runner/.cargo/bin
        steps:
            - uses: actions/checkout@v4
            - run: pipx install poetry
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.12
                  cache: poetry
            - run: make lint
            - run: |
                cargo audit
                rustc --version
            - uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/
                  ~/.cargo/git/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - run: cargo build --features=emulator
            #- run: cargo install cargo-llvm-cov
            #- name: Install cargo-nextest
            #  run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ~/.cargo/bin
            - run: |
                cargo fmt -- --check
                cargo clippy --all --all-targets --all-features -- -D warnings --deny=clippy::dbg_macro
