name: CI
on:
    workflow_dispatch:  # Allow manual triggering
    #PR?
    push:
        branches: [master,main]

jobs:
    check:
        runs-on: ubuntu-latest
        env:
            DEST_DIR: /home/runner/.cargo/bin
        steps:
            - uses: actions/checkout@v4
            #- uses: actions/cache@v4
            #  with:
            #    path: |
            #      ~/.cargo/bin/
            #      ~/.cargo/registry/
            #      ~/.cargo/git/
            #      target/
            #    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - run: |
                cargo install cargo-audit
                cargo audit
            - run: cargo build --features=emulator
            - run: pipx install poetry
            - run: make lint
            #setp python 3.12
            #- run: cargo install cargo-llvm-cov
            #- name: Install cargo-nextest
            #  run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ~/.cargo/bin
            - run: |
                cargo fmt -- --check
                cargo clippy --all --all-targets --all-features -- -D warnings --deny=clippy::dbg_macro
